using WorkItemTracker.Api.Exceptions;

namespace WorkItemTracker.Api.Domain;

public class WorkItem
{
    /// <summary>
    /// Surrogate primary key. Generated by the database on insert; clients never supply it.
    /// </summary>
    public int Id { get; private set; }

    public string Title { get; private set; } = string.Empty;

    public string? Description { get; private set; }

    public WorkItemStatus Status { get; private set; }

    public DateTime CreatedAt { get; private set; }

    // Required by EF Core
    private WorkItem()
    {
    }

    public static WorkItem Create(string title, string? description)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(title);

        var trimmed = title.Trim();
        if (trimmed.Length > 120)
        {
            throw new ValidationException("Title must be at most 120 characters.");
        }

        return new WorkItem
        {
            Title = trimmed,
            Description = string.IsNullOrWhiteSpace(description) ? null : description.Trim(),
            Status = WorkItemStatus.Todo,
            CreatedAt = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Applies an allowed status transition. Allowed: Todo → InProgress → Done.
    /// </summary>
    public void ChangeStatus(WorkItemStatus newStatus)
    {
        var isAllowed = Status switch
        {
            WorkItemStatus.Todo => newStatus == WorkItemStatus.InProgress,
            WorkItemStatus.InProgress => newStatus == WorkItemStatus.Done,
            _ => false
        };

        if (!isAllowed)
        {
            throw new InvalidStatusTransitionException(Status, newStatus);
        }

        Status = newStatus;
    }
}
